[build]
  publish = "dist"
  command = "pnpm build"

# Forzamos el bundler moderno de funciones
[functions.node_bundle]
  external_node_modules = []

# La detección de idioma se realiza en el navegador vía src/pages/index.astro

