[build]
  publish = "dist"
  command = "pnpm build"
  edge_functions = "netlify/edge-functions"

# FUNCIÓN 1: Captura el código de GitHub al iniciar sesión
[[edge_functions]]
  path = "/api/auth/callback"
  function = "auth"

# FUNCIÓN 2: Procesa el formulario y hace los commits directos
[[edge_functions]]
  path = "/api/save"
  function = "save"